name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Sync deployment fork here."
